In [ ]:
#BFS EXERCISE 1 :

class TreeNode :
  def __init__(self, data) :
    self.data = data
    self.children = []

root = TreeNode(1)
root.children = [TreeNode(2), TreeNode(3), TreeNode(4)]
root.children[1].children = [TreeNode(5), TreeNode(6)]
root.children[2].children = [TreeNode(7)]
root.children[1].children[0].children = [TreeNode(8), TreeNode(9)]

In [ ]:
from collections import deque

def BFS_Algorithm(root) :
  if root is None :
    return

  queue = deque([root]) #here we are creating and initializing a queue
  visited = []

  while queue :
    current = queue.popleft()
    visited.append(current.data)

    for child in current.children :
      queue.append(child)

  return visited


bfs_result = BFS_Algorithm(root)
print("BFS Traversal Sequence:", bfs_result)

BFS Traversal Sequence: [1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
#BFS EXERCISE 2 :

class TreeBinary :
    def __init__(self, data) :
      self.data = data
      self.left = None
      self.right = None


# create a binary Tree
root = TreeBinary(1)
root.left = TreeBinary(2)
root.right = TreeBinary(3)
root.left.left = TreeBinary(4)
root.left.right = TreeBinary(5)
root.right.left = TreeBinary(6)
root.right.right = TreeBinary(7)

In [ ]:
from collections import deque

def bfs(root) :
  if root is None :
    return

  queue = deque([root]) #here we are creating and initializing a queue
  visited = []

  while queue :
    node = queue.popleft()
    visited.append(node.data)

    if node.left :
      queue.append(node.left)
    if node.right :
      queue.append(node.right)

  return visited


bfs_result = bfs(root)
print("BFS Traversal Sequence:", bfs_result)

BFS Traversal Sequence: [1, 2, 3, 4, 5, 6, 7]


BFS EXERCICES

In [ ]:
#DFS Algorithm Exercices 1

def dfs_stack_binary_tree(root):
    if root is None:  # Handle the edge case of an empty tree
        return []

    stack = [root]  # Initialize the stack with the root node
    traversal = []  # To store the result of DFS

    while stack:
        node = stack.pop()  # Pop the top node from the stack
        traversal.append(node.data)  # Add the current node's data to traversal

        # Push the right child first, then the left child (to process left first)
        if node.right:
            stack.append(node.right)
        if node.left:
            stack.append(node.left)

    return traversal

# Create the binary tree
class TreeBinary:
    def __init__(self, data):
        self.data = data
        self.left = None
        self.right = None

# Define your binary tree
root = TreeBinary(1)
root.left = TreeBinary(2)
root.right = TreeBinary(3)
root.left.left = TreeBinary(4)
root.left.right = TreeBinary(5)
root.right.left = TreeBinary(6)
root.right.right = TreeBinary(7)

# Perform DFS using stack
result = dfs_stack_binary_tree(root)
print("DFS Traversal:", result)


DFS Traversal: [1, 2, 4, 5, 3, 6, 7]


In [ ]:
#DFS Algorithm Exercices 2

class TreeNode:
    def __init__(self, data):
        self.data = data
        self.children = []

def dfs_stack_non_binary_tree(root):
    if root is None:  # Handle the edge case of an empty tree
        return []

    stack = [root]  # Initialize the stack with the root node
    traversal = []  # To store the result of DFS

    while stack:
        node = stack.pop()  # Pop the top node from the stack
        traversal.append(node.data)  # Add the current node's data to traversal

        # Push children in reverse order to process left-to-right
        for child in reversed(node.children):
            stack.append(child)

    return traversal


# Define your non-binary tree
root = TreeNode(1)
root.children = [TreeNode(2), TreeNode(3), TreeNode(4)]
root.children[1].children = [TreeNode(5), TreeNode(6)]
root.children[2].children = [TreeNode(7)]
root.children[1].children[0].children = [TreeNode(8), TreeNode(9)]

# Perform DFS using stack
result = dfs_stack_non_binary_tree(root)
print("DFS Traversal (Non-Binary Tree):", result)


DFS Traversal (Non-Binary Tree): [1, 2, 3, 5, 8, 9, 6, 4, 7]


Exercises: DFS and BFS : Search from left-to-right. Initial state is ‘g’ and goal state is ‘d’

In [ ]:
from collections import deque

def bfs(graph, start, goal):
    visited = set()
    queue = deque([start])
    traversal = []

    while queue:
        node = queue.popleft()
        if node not in visited:
            visited.add(node)
            traversal.append(node)
            if node == goal:
                break
            queue.extend(graph[node])  # Add neighbors to the queue

    return traversal


In [ ]:
def dfs(graph, start, goal):
    visited = set()
    stack = [start]
    traversal = []

    while stack:
        node = stack.pop()
        if node not in visited:
            visited.add(node)
            traversal.append(node)
            if node == goal:
                break
            stack.extend(reversed(graph[node]))  # Add neighbors in reverse order

    return traversal


In [ ]:
graph = {
    'a': ['b', 'e'],
    'b': ['a', 'c', 'j'],
    'c': ['b', 'd', 'k'],
    'd': ['c', 'h'],
    'e': ['a', 'i', 'm'],
    'h': ['d', 'l', 'g'],  # 'h' connects to 'g'
    'i': ['e', 'j'],
    'j': ['b', 'i', 'k'],
    'k': ['c', 'j', 'p', 'g'],  # 'k' connects to 'g'
    'l': ['h'],
    'm': ['e'],
    'p': ['k'],
    'g': ['h', 'k']  # Add 'g' with its neighbors
}

In [ ]:
bfs_traversal = bfs(graph, 'g', 'd')
dfs_traversal = dfs(graph, 'g', 'd')

print("BFS Traversal:", bfs_traversal)
print("DFS Traversal:", dfs_traversal)


BFS Traversal: ['g', 'h', 'k', 'd']
DFS Traversal: ['g', 'h', 'd']


A start Algorithm

In [ ]:
import heapq

# Define the grid
grid = [
    [0, 0, 1, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 0],
    [1, 1, 0, 0]
]

# Directions (up, down, left, right)
directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]

# Manhattan Distance Heuristic Function (calculate the estimate code to travel btw these point )
def manhattan_distance(start, goal):
    return abs(start[0] - goal[0]) + abs(start[1] - goal[1])

# A* Algorithm Implementation
def a_star(start, goal):
    open_list = []
    closed_list = set()

    # Add the start node with f = g + h to the open_list (h : estimate cost to reach the goal)
    heapq.heappush(open_list, (0 + manhattan_distance(start, goal), 0, start))

    # Store parent for path reconstruction
    came_from = {}

    while open_list:
        _, g, current = heapq.heappop(open_list)

        # If the goal is reached, reconstruct the path
        if current == goal:
            path = []
            while current in came_from:
                path.append(current)
                current = came_from[current]
            path.append(start)
            path.reverse()
            return path

        closed_list.add(current)

        # Explore neighbors
        for dx, dy in directions:
            neighbor = (current[0] + dx, current[1] + dy)
            if 0 <= neighbor[0] < len(grid) and 0 <= neighbor[1] < len(grid[0]) and grid[neighbor[0]][neighbor[1]] == 0:
                if neighbor not in closed_list:
                    g_cost = g + 1
                    f_cost = g_cost + manhattan_distance(neighbor, goal)
                    heapq.heappush(open_list, (f_cost, g_cost, neighbor))
                    came_from[neighbor] = current

    return None  # Return None if no path is found

# Example usage
start = (0, 0)
goal = (3, 3)
path = a_star(start, goal)
print("Path:", path)


Path: [(0, 0), (1, 0), (2, 0), (2, 1), (2, 2), (3, 2), (3, 3)]


In [1]:
# Manual Scaling (Standardization)

import numpy as np

# Sample data (features in columns, samples in rows)
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Manual scaling function
def standardize(data):
    # Calculate mean and standard deviation for each feature (column)
    means = np.mean(data, axis=0)
    stds = np.std(data, axis=0)

    # Scale the data
    standardized_data = (data - means) / stds
    return standardized_data

# Applying standardization
scaled_data = standardize(data)

print("Standardized Data:\n", scaled_data)


Standardized Data:
 [[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


In [2]:
# Manual Normalization (Min-Max Scaling)

# Manual normalization function
def normalize(data):
    # Calculate min and max for each feature (column)
    mins = np.min(data, axis=0)
    maxs = np.max(data, axis=0)

    # Normalize the data
    normalized_data = (data - mins) / (maxs - mins)
    return normalized_data

# Applying normalization
normalized_data = normalize(data)

print("Normalized Data:\n", normalized_data)


Normalized Data:
 [[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]
